Make calls to make_filefs more consistent

diff --git a/bin/persist-makefs b/bin/persist-makefs
--- a/bin/persist-makefs
+++ b/bin/persist-makefs
@@ -150,7 +150,7 @@ main() {
 
         gather_device_info
         vmsg "Make rootfs.new"
-        make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")" ""
+        make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")"
         exit
 
     elif [ "$SET_EXPLORE" ]; then
@@ -219,7 +219,7 @@ main() {
 
             $MAKE_ROOTFS)
                 vmsg "Make rootfs"
-                make_filefs rootfs "$(gt "Create Root")" ""
+                make_filefs rootfs "$(gt "Create Root persistence")"
                 ;;
 
             $RESIZE_ROOTFS)
@@ -231,15 +231,15 @@ main() {
                     continue
                 fi
                 vmsg "Resize rootfs"
-                make_filefs rootfs.tmp "$(gt "Resize Root")" "${USED_SPACE[rootfs]}"  && continue
+                make_filefs rootfs.tmp "$(gt "Resize Root persistence")" || continue
 
-                if ! [ "$MADE_FS" = "rootfs.tmp" ]; then
-                    noisy_yes_no_box "$TITLE" "" \
-                        "$(gt "The resize rootfs has failed.")" \
-                        "$(pfgt "Shall I delete the %s file?" "[f]rootfs.tmp[/]")" \
-                        && rm -f $rootfs.tmp
-                    continue
-                fi
+                # if ! [ "$MADE_FS" = "rootfs.tmp" ]; then
+                #     noisy_yes_no_box "$TITLE" "" \
+                #         "$(gt "The resize rootfs has failed.")" \
+                #         "$(pfgt "Shall I delete the %s file?" "[f]rootfs.tmp[/]")" \
+                #         && rm -f $rootfs.tmp
+                #     continue
+                # fi
                 copy_filefs "$rootfs" "$rootfs.tmp" "${USED_SPACE[rootfs]}" || continue
                 mv -f $rootfs $rootfs.bak
                 mv -f $rootfs.tmp $rootfs
@@ -247,19 +247,18 @@ main() {
 
             $MAKE_ROOTFS_NEW)
                 vmsg "Make rootfs.new"
-                make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")" ""
+                make_filefs rootfs.new "$(gt "Create %s (for remastering)" rootfs.new)"
                 ;;
 
             $MAKE_HOMEFS)
                 vmsg "Make homefs"
-                make_filefs "homefs" "$(gt "Create Home")" "" "$SAFE_AVAIL" "$(gt "Create Home")"
+                make_filefs "homefs" "$(gt "Create Home persistence")"
                 ;;
 
             $RESIZE_HOMEFS)
                 vmsg "Resize homefs"
                 homefs="$FULL_PATH/homefs"
-                make_filefs "homefs.new" "$(gt "Resize Home")" "" "$SAFE_AVAIL" "$(gt "Resize Home")" \
-                    && continue
+                make_filefs "homefs.new" "$(gt "Resize Home persistence")" || continue
 
                 copy_filefs "$homefs" "$homefs.new" "${USED_SPACE[homefs]}"
                 ;;
